import { TRPCProvider } from "@/trpc/client";
import "./global.css";

export const metadata = {
  title: "Welcome to next-prisma-trpc",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  );
}
